# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.CharField(max_length=100, null=True, verbose_name='\u4e0a\u4f20\u4eba')),
                ('applicant', models.CharField(max_length=100, verbose_name='\u7533\u8bf7\u4eba')),
                ('application_time', models.DateTimeField(null=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('accounts_set', models.CharField(max_length=100, verbose_name='\u8d26\u5957')),
                ('material_category', models.CharField(max_length=100, verbose_name='\u7269\u8d44\u7c7b\u522b')),
                ('material_name', models.CharField(max_length=100, verbose_name='\u7269\u8d44\u540d\u79f0')),
                ('brand', models.CharField(max_length=30, null=True, verbose_name='\u54c1\u724c')),
                ('model', models.CharField(max_length=100, null=True, verbose_name='\u89c4\u683c\u578b\u53f7')),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='\u8ba1\u91cf\u5355\u4f4d')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='\u5907\u6ce8')),
                ('demand_department', models.CharField(blank=True, max_length=100, verbose_name='\u9700\u6c42\u90e8\u95e8')),
                ('equipment_name', models.CharField(blank=True, max_length=100, verbose_name='\u8bbe\u5907\u540d\u79f0')),
                ('equipment_model', models.CharField(blank=True, max_length=100, verbose_name='\u8bbe\u5907\u578b\u53f7')),
                ('manufacturers', models.CharField(blank=True, max_length=100, verbose_name='\u5382\u5bb6')),
                ('varified', models.CharField(blank=True, max_length=100, verbose_name='\u662f\u5426\u5ba1\u6838')),
                ('varified_time', models.DateTimeField(blank=True, verbose_name='\u5ba1\u6838\u65f6\u95f4')),
                ('varified_user_id', models.CharField(blank=True, max_length=100, verbose_name='\u5ba1\u6838\u4eba')),
                ('U8code', models.CharField(blank=True, max_length=100, verbose_name='U8\u7f16\u53f7')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'permissions': (('verify_application', 'can verify application'), ('change_application', 'Can change_application'), ('edit_u8code', 'Can edit U8code')),
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='./upload/')),
            ],
        ),
    ]
