# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockCode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codetable',
            options={'permissions': (('varify_application', 'can varify application'), ('change_application', 'Can change_application'), ('edit_u8code', 'Can edit U8code'))},
        ),
    ]
