# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCode', '0002_auto_20160829_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetable',
            name='U8code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='U8\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='codetable',
            name='demand_department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u9700\u6c42\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='codetable',
            name='equipment_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8bbe\u5907\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='codetable',
            name='equipment_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8bbe\u5907\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='codetable',
            name='manufacturers',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5382\u5bb6'),
        ),
        migrations.AlterField(
            model_name='codetable',
            name='varified',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u662f\u5426\u5ba1\u6838'),
        ),
        migrations.AlterField(
            model_name='codetable',
            name='varified_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5ba1\u6838\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='codetable',
            name='varified_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5ba1\u6838\u4eba'),
        ),
    ]
