# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 02:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockCode', '0003_auto_20160829_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetable',
            name='publisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
