# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 02:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockCode', '0004_codetable_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codetable',
            name='publisher',
        ),
        migrations.AddField(
            model_name='codetable',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
