# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockCode', '0006_codetable_group_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codetable',
            options={'permissions': (('varify_application', '\u5ba1\u6838\u65b0\u589e\u7f16\u7801\u7533\u8bf7'), ('change_application', '\u53d8\u66f4\u7f16\u7801\u7533\u8bf7'), ('edit_u8code', '\u4fee\u6539U8\u7f16\u53f7'))},
        ),
    ]
