# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCode', '0007_auto_20160907_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codetable',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='codetable',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='codetable',
            name='add_code_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u6dfb\u52a0\u7f16\u7801\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='codetable',
            name='add_code_time_userid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5ba1\u6838\u4eba'),
        ),
        migrations.AlterField(
            model_name='codetable',
            name='brand',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u54c1\u724c'),
        ),
    ]
