# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockCode', '0008_auto_20161015_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codetable',
            old_name='add_code_time_userid',
            new_name='add_code_time_username',
        ),
    ]
