# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCode', '0009_auto_20161015_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetable',
            name='add_completed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u662f\u5426\u6dfb\u52a0\u5b8c'),
        ),
    ]
