# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCode', '0010_codetable_add_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codetable',
            name='uploader',
        ),
        migrations.AddField(
            model_name='codetable',
            name='number',
            field=models.CharField(max_length=100, null=True, verbose_name='\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='codetable',
            name='remark',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u5907\u6ce8'),
        ),
    ]
