# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCode', '0011_auto_20161018_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProperty',
            fields=[
                ('material_category', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('storagearea', models.FloatField(blank=True, db_column='storageArea', null=True)),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute', models.CharField(blank=True, max_length=255, null=True)),
                ('domestic', models.IntegerField(blank=True, null=True)),
                ('purchase', models.IntegerField(blank=True, null=True)),
                ('import_field', models.IntegerField(blank=True, db_column='import', null=True)),
                ('productionconsumption', models.IntegerField(blank=True, db_column='productionConsumption', null=True)),
                ('manufacturing', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
