# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.AlterField(
            model_name='materialproperty',
            name='import_field',
            field=models.IntegerField(blank=True, db_column='import_field', null=True),
        ),
    ]
