# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCode', '0013_auto_20161101_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('measurement_unit', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('measurement_unit_group_code', models.CharField(max_length=255)),
                ('measurement_unit_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='materialproperty',
            name='import_field',
            field=models.IntegerField(blank=True, db_column='import', null=True),
        ),
    ]
