# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_num', models.FloatField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_of_deposit', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_in_figures', models.FloatField(blank=True, null=True)),
                ('amount_in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('document_num', models.CharField(blank=True, max_length=255, null=True)),
                ('closing_date', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.CharField(blank=True, max_length=255, null=True)),
                ('expiring_date', models.DateField(blank=True, null=True)),
                ('acceptance_bill', models.CharField(blank=True, max_length=255, null=True)),
                ('cash', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_finance', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_in_advance', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'permissions': (('query_payment', '\u67e5\u8be2\u4ed8\u6b3e\u5355'), ('edit_payment', '\u4fee\u6539\u4ed8\u6b3e\u5355')),
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_of_deposit', models.CharField(blank=True, max_length=255, null=True)),
                ('closing_date', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'permissions': (('query_supplier_payment', '\u67e5\u8be2\u4ed8\u6b3e\u5355\u4f9b\u5e94\u5546'), ('edit_supplier_payment', '\u4fee\u6539\u4ed8\u6b3e\u5355\u4f9b\u5e94\u5546')),
            },
        ),
    ]
