# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_location', models.CharField(blank=True, max_length=255, null=True)),
                ('record_date', models.DateTimeField(blank=True, null=True)),
                ('supplier_class', models.CharField(blank=True, max_length=255, null=True)),
                ('material_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('landline', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'supplierlist_optional_supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('archive_class', models.CharField(blank=True, max_length=255, null=True)),
                ('archive_id', models.CharField(blank=True, max_length=255, null=True)),
                ('review_document_id', models.CharField(blank=True, max_length=255, null=True)),
                ('material_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_class', models.CharField(blank=True, max_length=255, null=True)),
                ('review_class', models.CharField(blank=True, max_length=255, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('review_result', models.CharField(blank=True, max_length=255, null=True)),
                ('application_date', models.DateTimeField(blank=True, null=True)),
                ('review_table_situation', models.TextField(blank=True, null=True)),
                ('delay_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('review_remark', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('whether_cooperation', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('artificial_person', models.CharField(blank=True, max_length=255, null=True)),
                ('business_license_id', models.CharField(blank=True, max_length=255, null=True)),
                ('business_license_period', models.DateField(blank=True, null=True)),
                ('business_license_confirmation', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_capital', models.CharField(blank=True, max_length=255, null=True)),
                ('other_remark', models.CharField(blank=True, max_length=255, null=True)),
                ('certifcate_remark', models.CharField(blank=True, max_length=255, null=True)),
                ('company_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_information', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_1', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_position_1', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_telephone_1', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_2', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_position_2', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_telephone_2', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_3', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_position_3', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_telephone_3', models.CharField(blank=True, max_length=255, null=True)),
                ('qq', models.CharField(blank=True, db_column='QQ', max_length=255, null=True)),
                ('contact_remark', models.CharField(blank=True, max_length=255, null=True)),
                ('annual', models.CharField(blank=True, max_length=255, null=True)),
                ('position_abbr', models.CharField(blank=True, max_length=255, null=True)),
                ('qichacha', models.IntegerField(blank=True, null=True)),
                ('qichacha_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'supplierlist__supplier_list',
                'managed': False,
            },
        ),
    ]
