# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supplierlist',
            table='supplierlist_supplier_list',
        ),
    ]
