# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierList', '0003_auto_20160906_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierlist',
            options={'managed': False, 'permissions': (('query_supplier', 'Can query supplier'), ('add_new_supplier', 'Can add new supplier'), ('update_all_supplier', 'can update all supplier'), ('update_contract', 'Can update contract'))},
        ),
    ]
