# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplierList', '0005_auto_20160906_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionalsupplier',
            options={'managed': True, 'permissions': (('query_supplier', 'Can query supplier'), ('add_new_supplier', 'Can add new supplier'), ('update_all_supplier', 'can update all supplier'))},
        ),
        migrations.RenameField(
            model_name='supplierlist',
            old_name='certifcate_remark',
            new_name='certificate_remark',
        ),
        migrations.AlterField(
            model_name='optionalsupplier',
            name='record_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierlist',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierlist',
            name='qq',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
