# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierList', '0006_auto_20160906_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptionalSupplier',
            new_name='OptionalSupplierList',
        ),
    ]
