# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierList', '0008_auto_20160906_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierlist',
            options={'managed': True, 'permissions': (('query_supplier', 'Can query supplier'), ('add_new_supplier', 'Can add new supplier'), ('show_document', '\u663e\u793a\u4f9b\u5e94\u5546\u6863\u6848'), ('update_all_supplier', 'can update all supplier'), ('update_contract', 'Can update contract'))},
        ),
    ]
