# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierList', '0009_auto_20160907_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionalsupplierlist',
            options={'managed': True, 'permissions': (('query_optional_supplier', '\u67e5\u8be2\u5907\u9009\u4f9b\u5e94\u5546'), ('add_new_optional_supplier', '\u65b0\u589e\u5907\u9009\u4f9b\u5e94\u5546'), ('update_all_optional_supplier', '\u66f4\u65b0\u5907\u9009\u4f9b\u5e94\u5546\u4fe1\u606f'))},
        ),
        migrations.AlterModelOptions(
            name='supplierlist',
            options={'managed': True, 'permissions': (('query_supplier', '\u67e5\u8be2\u4f9b\u5e94\u5546'), ('add_new_supplier', '\u65b0\u589e\u4f9b\u5e94\u5546'), ('show_document', '\u663e\u793a\u4f9b\u5e94\u5546\u6863\u6848'), ('update_all_supplier', '\u66f4\u65b0\u4f9b\u5e94\u5546\u4fe1\u606f'), ('update_contract', '\u66f4\u65b0\u4f9b\u5e94\u5546\u8054\u7cfb\u4eba'))},
        ),
    ]
