# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierList', '0011_auto_20160907_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionalsupplierlist',
            options={'managed': True, 'permissions': (('query_optional_supplier', 'Can query supplier'), ('add_new_optional_supplier', 'Can add new optional supplier'), ('update_all_optional_supplier', '\u66f4\u65b0\u5907\u9009\u4f9b\u5e94\u5546\u4fe1\u606f'))},
        ),
    ]
