# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplierList', '0013_auto_20160908_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionalsupplierlist',
            options={'managed': True, 'permissions': (('query_optional_supplier', 'Can query optional supplier'), ('add_new_optional_supplier', 'Can add new optional supplier'), ('update_all_optional_supplier', 'can update all optional supplier'))},
        ),
    ]
