# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160906_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title_name',
            field=models.CharField(default='', max_length=100, verbose_name='\u7ea7\u522b'),
            preserve_default=False,
        ),
    ]
